# Generated by Django 5.0.2 on 2024-03-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="is_favorited",
            new_name="is_favorite",
        ),
    ]
